name: Build and Deploy to production

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore ./MinimalAPI/MinimalAPI.csproj

      - name: Build the Application
        run: dotnet build ./MinimalAPI/MinimalAPI.csproj --configuration Release

      - name: Publish the Application
        run: dotnet publish ./MinimalAPI/MinimalAPI.csproj --configuration Release --output ./publish

      - name: Create Zip of Published Files
        run: |
          zip -r release.zip ./publish
          echo "Zip file created"

      - name: Upload Artifact to Build Environment
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact
          path: ./release-artifact

      - name: Authenticate with Azure using OpenID (Entra ID)
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "nediev-webapp-production-westeurope-01"
          package: './release-artifact/release.zip'